# Generated by Django 3.2.7 on 2021-09-14 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210912_2140'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='staff',
        ),
        migrations.AddField(
            model_name='job',
            name='staff_id',
            field=models.ManyToManyField(related_name='user_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_jobs', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_tasks', to='projects.job'),
        ),
        migrations.AlterField(
            model_name='work',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_works', to='projects.job'),
        ),
        migrations.AlterField(
            model_name='work',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_works', to=settings.AUTH_USER_MODEL),
        ),
    ]
