# Generated by Django 3.2.7 on 2021-09-14 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_auto_20210914_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='staff_id',
            field=models.ManyToManyField(blank=True, related_name='user_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
