# Generated by Django 3.2.7 on 2021-09-15 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210915_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='work',
            name='start_time',
        ),
    ]
