# Generated by Django 3.2.7 on 2021-09-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210915_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
