# Generated by Django 3.2.6 on 2021-09-17 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_job_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_jobs', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to='projects.job'),
        ),
        migrations.AlterField(
            model_name='work',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_works', to='projects.job'),
        ),
        migrations.AlterField(
            model_name='work',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('post', models.ManyToManyField(default=None, to='projects.Work')),
                ('project_id', models.ManyToManyField(related_name='project_files', to='projects.Project')),
            ],
        ),
    ]
