# Generated by Django 3.2.7 on 2021-09-17 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.FileField(upload_to='projects/images/'),
        ),
    ]
