# Generated by Django 3.2.5 on 2021-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210917_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
