# Generated by Django 3.2.6 on 2021-09-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('publishDate', models.DateTimeField()),
                ('text', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('post', models.ManyToManyField(default=None, to='projects.Work')),
                ('project_id', models.ManyToManyField(related_name='project_files', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
