# Generated by Django 3.2.7 on 2021-09-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210921_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
