# Generated by Django 3.2.7 on 2021-09-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210922_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='upload_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
