# Generated by Django 3.2.7 on 2021-09-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210923_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_job', to='projects.job'),
        ),
    ]
